### PR TITLE
freetype: fix build system

### PR DESCRIPTION
**Pull request by rofl0r**
see commits

note: these 2 patches should be applied to all branches, including the not-yet-existing 2.0.9 branch.

### CODE REVIEW

**Comment by ericoporto** [comment]
@rofl0r , I imagine people just forgot to look for this Pull Request (I know I just check the ags repository issues). Can I get some context on it, is the current one broken? Was there an issue somewhere mentioning it?

**Comment by rofl0r** [comment]
i tried to use the makefiles in this repo and ran into errors, then diffed the original sources (working) against the ones here, this is the result. should still be needed.

**Comment by ericoporto** [comment]
Paging @ivan-mogilko and @morganwillcock who are the ones I know have write access to the repo.

**Comment by ivan-mogilko** [comment]
Oh, I am sorry, probably missed this, and I for some reason I did not have notifications turned on for this repository.

@rofl0r looking at the changes on github, there's this symbol `ÿ` met in numerous places, is this the "bogus \xff character" you were speaking about?

**Comment by rofl0r** [comment]
@ivan-mogilko yes, that's the character i was talking about.

**Pull request merged**
